export default {
    products : [
        {
            _id:'1',
            name:'Hiskywin Full Zip Running Shirts Thermal Workout',
            category:'Shirts',
            image:'/images/product-1.jpg',
            price:60,
            brand:'Hiskywin',
            rating:'4.5',
            numReviews: 10,
            countInStocks: 6,
        },
        {
            _id:'2',
            name:'Hiskywin Full Zip Running Shirts Thermal Workout',
            category:'Shirts',
            image:'/images/product-2.jpg',
            price:60,
            brand:'Hiskywin',
            rating:'4.5',
            numReviews: 10,
            countInStocks: 6,
        },
        {
            _id:'3',
            name:'Hiskywin Full Zip Running Shirts Thermal Workout',
            category:'Shirts',
            image:'/images/product-3.jpg',
            price:60,
            brand:'Hiskywin',
            rating:'4.5',
            numReviews: 10,
            countInStocks: 6,
        },
        {
            _id:'4',
            name:'Hiskywin Full Zip Running Shirts Thermal Workout',
            category:'Shirts',
            image:'/images/product-4.jpg',
            price:60,
            brand:'Hiskywin',
            rating:'4.5',
            numReviews: 10,
            countInStocks: 6,
        },
        {
            _id:'5',
            name:'Hiskywin Full Zip Running Shirts Thermal Workout',
            category:'Shirts',
            image:'/images/product-5.jpg',
            price:60,
            brand:'Hiskywin',
            rating:'4.5',
            numReviews: 10,
            countInStocks: 6,
        },
        {
            _id:'6',
            name:'Hiskywin Full Zip Running Shirts Thermal Workout',
            category:'Shirts',
            image:'/images/product-6.jpg',
            price:60,
            brand:'Hiskywin',
            rating:'4.5',
            numReviews: 10,
            countInStocks: 6,
        }
    ]
};